name: docker

on:
  push:
    tags:
      - "*"
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  slug: "klutchell/dnscrypt-proxy"
  platforms: "linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"

jobs:
  build:
    runs-on: latest

    services:
      registry:
        image: registry:2.7.1
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v3

      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: docker.io/${{ env.slug }},ghcr.io/${{ env.slug }}
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=semver,pattern={{version}}

      - uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - uses: docker/build-push-action@v3
        with:
          platforms: ${{ env.platforms }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: localhost:5000/${{ env.slug }}:local
          cache-to: type=gha,mode=max
          cache-from: |
            type=gha
            ${{ steps.meta.outputs.tags }}
          push: true

      - uses: docker/setup-qemu-action@v2

      - name: Run tests
        run: |
          for platform in $(tr ',' '\n' <<< "${{ env.platforms }}") ; do
            docker pull --platform ${platform} localhost:5000/${{ env.slug }}:local
            docker run -d --name sut localhost:5000/${{ env.slug }}:local
            sleep 60
            docker exec sut dnscrypt-proxy -version | tee /dev/stderr | grep -wq "$(head -n1 VERSION)" || { docker logs sut ; exit 1 ; }
            docker run --rm --link sut uzyexe/drill -p 5053 dnscrypt.info @sut | tee /dev/stderr | grep -wq NOERROR || { docker logs sut ; exit 1 ; }
            docker logs sut
            docker rm -f sut
          done

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: akhilerm/tag-push-action@v2.0.0
        if: github.actor == github.repository_owner
        with:
          src: localhost:5000/${{ env.slug }}:local
          dst: |
            ${{ steps.meta.outputs.tags }}
